<?php

return [
  'name' => 'nfe_num',
  'setup' => [
    'type' => 'num',
    'length' => 500,
    'default' => '',
    'checkInput' => false,
    'checkOutput' => false,
    'fillMissing' => false,
  ],
  'types' => [
    'NF_NUMERO' => [
      'model' => 'CTE:ER32',
      'nullable' => true,
      'required' => false,
    ],
  ],
  'parser' => 'collection',
  'definitions' => [
    0 => [
      'type' => 'string',
      'regex' => '[1-9]{1}[0-9]{0,8}',
      'nullable' => true,
      'required' => false,
      'element' => 'NF_NUMERO',
    ],
    1 => [
      'type' => 'string',
      'regex' => '0|[1-9]{1}[0-9]{0,2}',
      'element' => 'NF_SERIE',
    ],
    2 => [
      'type' => 'string',
      'regex' => '[123567][0-9]([0-9][1-9]|[1-9][0-9])',
      'element' => 'NF_CFOP',
    ],
    3 => [
      'type' => 'string',
      'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
      'element' => 'NF_VL',
    ],
    4 => [
      'type' => 'string',
      'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
      'element' => 'NF_PROD_VL',
    ],
    5 => [
      'type' => 'string',
      'regex' => '(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d([\\-,\\+](0[0-9]|10|11):00|([\\+](12):00))',
      'element' => 'DATA_EMISSAO',
    ],
    6 => [
      'type' => 'string',
      'regex' => '[0-9]{44}',
      'element' => 'NF_CHAVE',
    ],
    7 => [
      'type' => 'enum',
      'enum' => [
        0 => '1',
        1 => '2',
      ],
      'element' => 'NF_TP_OPERACAO',
    ],
    8 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XNOME',
    ],
    9 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XFANT',
    ],
    10 => [
      'type' => 'string',
      'regex' => '[0-9]{6,14}',
      'element' => 'DEST_FONE',
    ],
    11 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_EMAIL',
    ],
    12 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XLGR',
    ],
    13 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_NRO',
    ],
    14 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XCPL',
    ],
    15 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XBAIRRO',
    ],
    16 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XMUN',
    ],
    17 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'DEST_CMUN',
    ],
    18 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'DEST_CEP',
    ],
    19 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'DEST_XUF',
    ],
    20 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'DEST_CPAIS',
    ],
    21 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XPAIS',
    ],
    22 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EXPED_XLGR',
    ],
    23 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EXPED_NRO',
    ],
    24 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EXPED_XCPL',
    ],
    25 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EXPED_XBAIRRO',
    ],
    26 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EXPED_XMUN',
    ],
    27 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'EXPED_CMUN',
    ],
    28 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'EXPED_CEP',
    ],
    29 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'EXPED_XUF',
    ],
    30 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'EXPED_CPAIS',
    ],
    31 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EXPED_XPAIS',
    ],
    32 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RECEB_XLGR',
    ],
    33 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RECEB_NRO',
    ],
    34 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RECEB_XCPL',
    ],
    35 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RECEB_XBAIRRO',
    ],
    36 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RECEB_XMUN',
    ],
    37 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'RECEB_CMUN',
    ],
    38 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'RECEB_CEP',
    ],
    39 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'RECEB_XUF',
    ],
    40 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'RECEB_CPAIS',
    ],
    41 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RECEB_XPAIS',
    ],
    42 => [
      'type' => 'string',
      'regex' => '[0-9]{0,14}|ISENTO',
      'element' => 'EMIT_IE',
    ],
    43 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XNOME',
    ],
    44 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XFANT',
    ],
    45 => [
      'type' => 'string',
      'regex' => '[0-9]{6,14}',
      'element' => 'EMIT_FONE',
    ],
    46 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_EMAIL',
    ],
    47 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XLGR',
    ],
    48 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_NRO',
    ],
    49 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XCPL',
    ],
    50 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XBAIRRO',
    ],
    51 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XMUN',
    ],
    52 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'EMIT_CMUN',
    ],
    53 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'EMIT_CEP',
    ],
    54 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'EMIT_XUF',
    ],
    55 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'EMIT_CPAIS',
    ],
    56 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XPAIS',
    ],
  ],
];