<?php

return [
  'name' => 'nfe_assoc',
  'extra' => [
    'NFE' => [
      'type' => 'string',
      'element' => 'NFE',
      'maxLength' => 13,
      'minLength' => 0,
      'expression' => 'concat(NF_NUMERO,"-",NF_SERIE)',
    ],
  ],
  'setup' => [
    'type' => 'assoc',
    'header' => true,
    'length' => 1000,
    'default' => '',
    'maxItems' => 150,
    'checkInput' => true,
    'maxRecords' => 15000,
    'checkOutput' => true,
    'fillMissing' => true,
  ],
  'types' => [
    'NF_PEDIDO' => [
      'type' => 'string',
      'maxLength' => 100,
      'minLength' => 0,
    ],
    'NF_ESPECIE' => [
      'model' => 'NFE:ER36',
      'default' => 'DIVERSOS',
      'required' => true,
    ],
  ],
  'parser' => 'csv',
  'definitions' => [
    0 => [
      'type' => 'numeric',
      'element' => 'EMIT_CNP',
      'maxLength' => 100,
      'minLength' => 0,
    ],
    1 => [
      'type' => 'string',
      'regex' => '[0-9]{2,14}',
      'element' => 'EMIT_CNP',
    ],
    2 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XNOME',
    ],
    3 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XFANT',
    ],
    4 => [
      'type' => 'string',
      'regex' => '[0-9]{6,14}',
      'element' => 'EMIT_FONE',
    ],
    5 => [
      'type' => 'string',
      'regex' => '[^@]+@[^\\.]+\\..+',
      'element' => 'EMIT_EMAIL',
    ],
    6 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XCPL',
    ],
    7 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_NRO',
    ],
    8 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XCPL',
    ],
    9 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XBAIRRO',
    ],
    10 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XMUN',
    ],
    11 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'EMIT_CMUN',
    ],
    12 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'EMIT_CEP',
    ],
    13 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'EMIT_UF',
    ],
    14 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'EMIT_CPAIS',
    ],
    15 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'EMIT_XPAIS',
    ],
    16 => [
      'type' => 'string',
      'regex' => '[0-9]{14}',
      'nullable' => true,
      'minLength' => 14,
      'maxLength' => 14,
      'element' => 'DEST_CNP',
    ],
    17 => [
      'type' => 'string',
      'regex' => '[0-9]{11}',
      'nullable' => true,
      'minLength' => 11,
      'maxLength' => 11,
      'element' => 'DEST_CNP',
    ],
    18 => [
      'type' => 'string',
      'regex' => '[0-9]{2,14}',
      'element' => 'DEST_CNP',
    ],
    19 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XNOME',
    ],
    20 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XFANT',
    ],
    21 => [
      'type' => 'string',
      'regex' => '[0-9]{6,14}',
      'element' => 'DEST_FONE',
    ],
    22 => [
      'type' => 'string',
      'regex' => '[^@]+@[^\\.]+\\..+',
      'element' => 'DEST_EMAIL',
    ],
    23 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XLGR',
    ],
    24 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_NRO',
    ],
    25 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XCPL',
    ],
    26 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XBAIRRO',
    ],
    27 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'DEST_CMUN',
    ],
    28 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XMUN',
    ],
    29 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'DEST_CEP',
    ],
    30 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'DEST_UF',
    ],
    31 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'DEST_CPAIS',
    ],
    32 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'DEST_XPAIS',
    ],
    33 => [
      'type' => 'string',
      'regex' => '[0-9]{14}',
      'nullable' => true,
      'minLength' => 14,
      'maxLength' => 14,
      'element' => 'RETIRA_CNP',
    ],
    34 => [
      'type' => 'string',
      'regex' => '[0-9]{11}',
      'nullable' => true,
      'minLength' => 11,
      'maxLength' => 11,
      'element' => 'RETIRA_CNP',
    ],
    35 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RETIRA_XLGR',
    ],
    36 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RETIRA_NRO',
    ],
    37 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RETIRA_XCPL',
    ],
    38 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RETIRA_XBAIRRO',
    ],
    39 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'RETIRA_CMUN',
    ],
    40 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RETIRA_XMUN',
    ],
    41 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'RETIRA_CEP',
    ],
    42 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'RETIRA_UF',
    ],
    43 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'RETIRA_CPAIS',
    ],
    44 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'RETIRA_XPAIS',
    ],
    45 => [
      'type' => 'string',
      'regex' => '[0-9]{14}',
      'nullable' => true,
      'minLength' => 14,
      'maxLength' => 14,
      'element' => 'ENTREGA_CNP',
    ],
    46 => [
      'type' => 'string',
      'regex' => '[0-9]{11}',
      'nullable' => true,
      'minLength' => 11,
      'maxLength' => 11,
      'element' => 'ENTREGA_CNP',
    ],
    47 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'ENTREGA_XLGR',
    ],
    48 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'ENTREGA_NRO',
    ],
    49 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'ENTREGA_XCPL',
    ],
    50 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'ENTREGA_XBAIRRO',
    ],
    51 => [
      'type' => 'string',
      'regex' => '[0-9]{7}',
      'element' => 'ENTREGA_CMUN',
    ],
    52 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'ENTREGA_XMUN',
    ],
    53 => [
      'type' => 'string',
      'regex' => '[0-9]{8}',
      'element' => 'ENTREGA_CEP',
    ],
    54 => [
      'type' => 'enum',
      'enum' => [
        0 => 'AC',
        1 => 'AL',
        2 => 'AM',
        3 => 'AP',
        4 => 'BA',
        5 => 'CE',
        6 => 'DF',
        7 => 'ES',
        8 => 'GO',
        9 => 'MA',
        10 => 'MG',
        11 => 'MS',
        12 => 'MT',
        13 => 'PA',
        14 => 'PB',
        15 => 'PE',
        16 => 'PI',
        17 => 'PR',
        18 => 'RJ',
        19 => 'RN',
        20 => 'RO',
        21 => 'RR',
        22 => 'RS',
        23 => 'SC',
        24 => 'SE',
        25 => 'SP',
        26 => 'TO',
        27 => 'EX',
      ],
      'element' => 'ENTREGA_UF',
    ],
    55 => [
      'type' => 'string',
      'regex' => '[0-9]{1,4}',
      'element' => 'ENTREGA_CPAIS',
    ],
    56 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'element' => 'ENTREGA_XPAIS',
    ],
    57 => [
      'type' => 'string',
      'regex' => '[1-9]{1}[0-9]{0,8}',
      'element' => 'NF_NUMERO',
    ],
    58 => [
      'type' => 'string',
      'regex' => '0|[1-9]{1}[0-9]{0,2}',
      'element' => 'NF_SERIE',
    ],
    59 => [
      'type' => 'string',
      'regex' => '[0-9]{44}',
      'element' => 'NFE_CHAVE',
    ],
    60 => [
      'type' => 'string',
      'regex' => '[123567][0-9]([0-9][1-9]|[1-9][0-9])',
      'element' => 'NFE_CFOP',
    ],
    61 => [
      'type' => 'string',
      'maxLength' => 100,
      'minLength' => 0,
      'element' => 'NF_PEDIDO',
    ],
    62 => [
      'type' => 'string',
      'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
      'element' => 'NF_VALOR',
    ],
    63 => [
      'type' => 'string',
      'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
      'element' => 'NF_VL_PROD',
    ],
    64 => [
      'type' => 'decimal',
      'dec_sep' => '.',
      'element' => 'NF_PESO',
      'decimals' => 2,
      'maxLength' => 100,
      'minLength' => 0,
    ],
    65 => [
      'type' => 'integer',
      'element' => 'NF_VOLUMES',
      'maxLength' => 100,
      'minLength' => 0,
    ],
    66 => [
      'type' => 'string',
      'element' => 'NF_NATUREZA',
      'maxLength' => 100,
      'minLength' => 0,
    ],
    67 => [
      'type' => 'string',
      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
      'default' => 'DIVERSOS',
      'required' => true,
      'element' => 'NF_ESPECIE',
    ],
    68 => [
      'type' => 'datetime',
      'format' => 'yyyy-mm-dd hh:ii:ss',
      'element' => 'DATA_EMISSAO',
      'maxLength' => 100,
      'minLength' => 0,
    ],
    69 => [
      'enum' => [
        0 => 'E',
        1 => 'S',
      ],
      'type' => 'enum',
      'element' => 'NF_TP_OPERACAO',
      'maxLength' => 100,
      'minLength' => 0,
    ],
  ],
];