<?php

return [
  'name' => 'nfe',
  'extra' => [
    'NF_DATA' => [
      'type' => 'datetime',
      'element' => 'NF_DATA',
      'expression' => 'substr(NF_DHEMI, 0, 10)',
    ],
    'NF_HORA' => [
      'type' => 'datetime',
      'format' => 'hh:ii:ss',
      'element' => 'NF_HORA',
      'expression' => 'substr(NF_DHEMI, 11, 8)',
    ],
  ],
  'setup' => [
    'pivot' => 'nfeProc',
    'length' => 500,
    'default' => NULL,
    'maxDepth' => 512,
    'maxItems' => 4096,
    'checkInput' => true,
    'maxRecords' => 15000,
    'checkOutput' => false,
    'fillMissing' => false,
  ],
  'parser' => 'xml',
  'definitions' => [
    'nfeProc' => [
      'key' => '',
      'elements' => [
        'NFe' => [
          'key' => '',
          'elements' => [
            'infNFe' => [
              'key' => '',
              'elements' => [
                'ide' => [
                  'key' => '',
                  'elements' => [
                    'cDV' => [
                      'type' => 'string',
                      'regex' => '[0-9]{1}',
                      'element' => 'NF_DV',
                    ],
                    'nNF' => [
                      'type' => 'string',
                      'regex' => '[1-9]{1}[0-9]{0,8}',
                      'element' => 'NF_NUMERO',
                    ],
                    'dhEmi' => [
                      'type' => 'string',
                      'regex' => '(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d([\\-,\\+](0[0-9]|10|11):00|([\\+](12):00))',
                      'element' => 'NF_DHEMI',
                    ],
                    'serie' => [
                      'type' => 'string',
                      'regex' => '0|[1-9]{1}[0-9]{0,2}',
                      'element' => 'NF_SERIE',
                    ],
                    'tpAmb' => [
                      'type' => 'enum',
                      'enum' => [
                        0 => '1',
                        1 => '2',
                      ],
                      'element' => 'NF_AMB',
                    ],
                  ],
                  'maxItems' => 1,
                  'minItems' => 1,
                ],
                'dest' => [
                  'key' => '',
                  'elements' => [
                    'IE' => [
                      'type' => 'string',
                      'regex' => '[0-9]{2,14}',
                      'element' => 'DEST_CNP',
                    ],
                    'CPF' => [
                      'type' => 'string',
                      'regex' => '[0-9]{11}',
                      'nullable' => true,
                      'minLength' => 11,
                      'maxLength' => 11,
                      'element' => 'DEST_CNP',
                    ],
                    'CNPJ' => [
                      'type' => 'string',
                      'regex' => '[0-9]{14}',
                      'nullable' => true,
                      'minLength' => 14,
                      'maxLength' => 14,
                      'element' => 'DEST_CNP',
                    ],
                    'fone' => [
                      'type' => 'string',
                      'regex' => '[0-9]{6,14}',
                      'element' => 'DEST_FONE',
                    ],
                    'email' => [
                      'type' => 'string',
                      'regex' => '[^@]+@[^\\.]+\\..+',
                      'element' => 'DEST_EMAIL',
                    ],
                    'xFant' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'DEST_XFANT',
                    ],
                    'xNome' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'DEST_XNOME',
                    ],
                    'enderDest' => [
                      'key' => '',
                      'elements' => [
                        'UF' => [
                          'type' => 'enum',
                          'enum' => [
                            0 => 'AC',
                            1 => 'AL',
                            2 => 'AM',
                            3 => 'AP',
                            4 => 'BA',
                            5 => 'CE',
                            6 => 'DF',
                            7 => 'ES',
                            8 => 'GO',
                            9 => 'MA',
                            10 => 'MG',
                            11 => 'MS',
                            12 => 'MT',
                            13 => 'PA',
                            14 => 'PB',
                            15 => 'PE',
                            16 => 'PI',
                            17 => 'PR',
                            18 => 'RJ',
                            19 => 'RN',
                            20 => 'RO',
                            21 => 'RR',
                            22 => 'RS',
                            23 => 'SC',
                            24 => 'SE',
                            25 => 'SP',
                            26 => 'TO',
                            27 => 'EX',
                          ],
                          'element' => 'DEST_UF',
                        ],
                        'CEP' => [
                          'type' => 'string',
                          'regex' => '[0-9]{8}',
                          'element' => 'DEST_CEP',
                        ],
                        'nro' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'DEST_NRO',
                        ],
                        'cMun' => [
                          'type' => 'string',
                          'regex' => '[0-9]{7}',
                          'element' => 'DEST_CMUN',
                        ],
                        'cSiafi' => [
                          'type' => 'string',
                          'regex' => '[0-9]{4}',
                          'element' => 'DEST_SIAFI',
                        ],
                        'xCpl' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'DEST_XCPL',
                        ],
                        'xLgr' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'DEST_XLGR',
                        ],
                        'xMun' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'DEST_XMUN',
                        ],
                        'cPais' => [
                          'type' => 'string',
                          'regex' => '[0-9]{1,4}',
                          'element' => 'DEST_CPAIS',
                        ],
                        'xPais' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'DEST_XPAIS',
                        ],
                        'xBairro' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'DEST_XBAIRRO',
                        ],
                      ],
                      'maxItems' => 1,
                      'minItems' => 1,
                    ],
                  ],
                  'maxItems' => 1,
                  'minItems' => 1,
                ],
                'emit' => [
                  'key' => '',
                  'elements' => [
                    'IE' => [
                      'type' => 'string',
                      'regex' => '[0-9]{2,14}',
                      'element' => 'EMIT_CNP',
                    ],
                    'CPF' => [
                      'type' => 'string',
                      'regex' => '[0-9]{11}',
                      'nullable' => true,
                      'minLength' => 11,
                      'maxLength' => 11,
                      'element' => 'EMIT_CNP',
                    ],
                    'CNPJ' => [
                      'type' => 'string',
                      'regex' => '[0-9]{14}',
                      'nullable' => true,
                      'minLength' => 14,
                      'maxLength' => 14,
                      'element' => 'EMIT_CNP',
                    ],
                    'fone' => [
                      'type' => 'string',
                      'regex' => '[0-9]{6,14}',
                      'element' => 'EMIT_FONE',
                    ],
                    'email' => [
                      'type' => 'string',
                      'regex' => '[^@]+@[^\\.]+\\..+',
                      'element' => 'EMIT_EMAIL',
                    ],
                    'xFant' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'EMIT_XFANT',
                    ],
                    'xNome' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'EMIT_XNOME',
                    ],
                    'enderEmit' => [
                      'key' => '',
                      'elements' => [
                        'UF' => [
                          'type' => 'enum',
                          'enum' => [
                            0 => 'AC',
                            1 => 'AL',
                            2 => 'AM',
                            3 => 'AP',
                            4 => 'BA',
                            5 => 'CE',
                            6 => 'DF',
                            7 => 'ES',
                            8 => 'GO',
                            9 => 'MA',
                            10 => 'MG',
                            11 => 'MS',
                            12 => 'MT',
                            13 => 'PA',
                            14 => 'PB',
                            15 => 'PE',
                            16 => 'PI',
                            17 => 'PR',
                            18 => 'RJ',
                            19 => 'RN',
                            20 => 'RO',
                            21 => 'RR',
                            22 => 'RS',
                            23 => 'SC',
                            24 => 'SE',
                            25 => 'SP',
                            26 => 'TO',
                            27 => 'EX',
                          ],
                          'element' => 'EMIT_UF',
                        ],
                        'CEP' => [
                          'type' => 'string',
                          'regex' => '[0-9]{8}',
                          'element' => 'EMIT_CEP',
                        ],
                        'nro' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'EMIT_NRO',
                        ],
                        'cMun' => [
                          'type' => 'string',
                          'regex' => '[0-9]{7}',
                          'element' => 'EMIT_CMUN',
                        ],
                        'cSiafi' => [
                          'type' => 'string',
                          'regex' => '[0-9]{4}',
                          'element' => 'EMIT_SIAFI',
                        ],
                        'xCpl' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'EMIT_XCPL',
                        ],
                        'xLgr' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'EMIT_XLGR',
                        ],
                        'xMun' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'EMIT_XMUN',
                        ],
                        'cPais' => [
                          'type' => 'string',
                          'regex' => '[0-9]{1,4}',
                          'element' => 'EMIT_CPAIS',
                        ],
                        'xPais' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'EMIT_XPAIS',
                        ],
                        'xBairro' => [
                          'type' => 'string',
                          'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                          'element' => 'EMIT_XBAIRRO',
                        ],
                      ],
                      'maxItems' => 1,
                      'minItems' => 1,
                    ],
                  ],
                  'maxItems' => 1,
                  'minItems' => 1,
                ],
                'total' => [
                  'key' => '',
                  'elements' => [
                    'ICMSTot' => [
                      'key' => '',
                      'elements' => [
                        'vBC' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_BC_ICMS',
                        ],
                        'vNF' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VALOR',
                        ],
                        'vST' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VL_ICMS_ST',
                        ],
                        'vSeg' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VL_SEG',
                        ],
                        'vBCST' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_BC_ICMSST',
                        ],
                        'vICMS' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VL_ICMS',
                        ],
                        'vProd' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VL_PROD',
                        ],
                        'vFrete' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VL_FRETE',
                        ],
                        'vICMSDeson' => [
                          'type' => 'string',
                          'regex' => '0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?',
                          'element' => 'NF_VL_ICMS_DES',
                        ],
                      ],
                      'maxItems' => 1,
                      'minItems' => 1,
                    ],
                  ],
                  'maxItems' => 1,
                  'minItems' => 1,
                ],
                'retira' => [
                  'key' => '',
                  'elements' => [
                    'UF' => [
                      'type' => 'enum',
                      'enum' => [
                        0 => 'AC',
                        1 => 'AL',
                        2 => 'AM',
                        3 => 'AP',
                        4 => 'BA',
                        5 => 'CE',
                        6 => 'DF',
                        7 => 'ES',
                        8 => 'GO',
                        9 => 'MA',
                        10 => 'MG',
                        11 => 'MS',
                        12 => 'MT',
                        13 => 'PA',
                        14 => 'PB',
                        15 => 'PE',
                        16 => 'PI',
                        17 => 'PR',
                        18 => 'RJ',
                        19 => 'RN',
                        20 => 'RO',
                        21 => 'RR',
                        22 => 'RS',
                        23 => 'SC',
                        24 => 'SE',
                        25 => 'SP',
                        26 => 'TO',
                        27 => 'EX',
                      ],
                      'element' => 'RETIRA_UF',
                    ],
                    'CEP' => [
                      'type' => 'string',
                      'regex' => '[0-9]{8}',
                      'element' => 'RETIRA_CEP',
                    ],
                    'CPF' => [
                      'type' => 'string',
                      'regex' => '[0-9]{11}',
                      'nullable' => true,
                      'minLength' => 11,
                      'maxLength' => 11,
                      'element' => 'RETIRA_CNP',
                    ],
                    'nro' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'RETIRA_NRO',
                    ],
                    'CNPJ' => [
                      'type' => 'string',
                      'regex' => '[0-9]{14}',
                      'nullable' => true,
                      'minLength' => 14,
                      'maxLength' => 14,
                      'element' => 'RETIRA_CNP',
                    ],
                    'cMun' => [
                      'type' => 'string',
                      'regex' => '[0-9]{7}',
                      'element' => 'RETIRA_CMUN',
                    ],
                    'xCpl' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'RETIRA_XCPL',
                    ],
                    'xLgr' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'RETIRA_XLGR',
                    ],
                    'xMun' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'RETIRA_XMUN',
                    ],
                    'cPais' => [
                      'type' => 'string',
                      'regex' => '[0-9]{1,4}',
                      'element' => 'RETIRA_CPAIS',
                    ],
                    'xPais' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'RETIRA_XPAIS',
                    ],
                    'xBairro' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'RETIRA_XBAIRRO',
                    ],
                  ],
                  'maxItems' => 1,
                  'minItems' => 1,
                ],
                'entrega' => [
                  'key' => '',
                  'elements' => [
                    'UF' => [
                      'type' => 'enum',
                      'enum' => [
                        0 => 'AC',
                        1 => 'AL',
                        2 => 'AM',
                        3 => 'AP',
                        4 => 'BA',
                        5 => 'CE',
                        6 => 'DF',
                        7 => 'ES',
                        8 => 'GO',
                        9 => 'MA',
                        10 => 'MG',
                        11 => 'MS',
                        12 => 'MT',
                        13 => 'PA',
                        14 => 'PB',
                        15 => 'PE',
                        16 => 'PI',
                        17 => 'PR',
                        18 => 'RJ',
                        19 => 'RN',
                        20 => 'RO',
                        21 => 'RR',
                        22 => 'RS',
                        23 => 'SC',
                        24 => 'SE',
                        25 => 'SP',
                        26 => 'TO',
                        27 => 'EX',
                      ],
                      'element' => 'ENTREGA_UF',
                    ],
                    'CEP' => [
                      'type' => 'string',
                      'regex' => '[0-9]{8}',
                      'element' => 'ENTREGA_CEP',
                    ],
                    'CPF' => [
                      'type' => 'string',
                      'regex' => '[0-9]{11}',
                      'nullable' => true,
                      'minLength' => 11,
                      'maxLength' => 11,
                      'element' => 'ENTREGA_CNP',
                    ],
                    'nro' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'ENTREGA_NRO',
                    ],
                    'CNPJ' => [
                      'type' => 'string',
                      'regex' => '[0-9]{14}',
                      'nullable' => true,
                      'minLength' => 14,
                      'maxLength' => 14,
                      'element' => 'ENTREGA_CNP',
                    ],
                    'cMun' => [
                      'type' => 'string',
                      'regex' => '[0-9]{7}',
                      'element' => 'ENTREGA_CMUN',
                    ],
                    'xCpl' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'ENTREGA_XCPL',
                    ],
                    'xLgr' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'ENTREGA_XLGR',
                    ],
                    'xMun' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'ENTREGA_XMUN',
                    ],
                    'cPais' => [
                      'type' => 'string',
                      'regex' => '[0-9]{1,4}',
                      'element' => 'ENTREGA_CPAIS',
                    ],
                    'xPais' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'ENTREGA_XPAIS',
                    ],
                    'xBairro' => [
                      'type' => 'string',
                      'regex' => '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}',
                      'element' => 'ENTREGA_XBAIRRO',
                    ],
                  ],
                  'maxItems' => 1,
                  'minItems' => 1,
                ],
              ],
              'maxItems' => 1,
              'minItems' => 1,
            ],
          ],
          'maxItems' => 1,
          'minItems' => 1,
        ],
        'protNFe' => [
          'key' => '',
          'elements' => [
            'infProt' => [
              'key' => '',
              'elements' => [
                'chNFe' => [
                  'type' => 'string',
                  'regex' => '[0-9]{44}',
                  'element' => 'NFE_CHAVE',
                ],
                'nProt' => [
                  'type' => 'string',
                  'regex' => '[0-9]{15}',
                  'element' => 'NFE_PROTOCOLO',
                ],
              ],
              'maxItems' => 1,
              'minItems' => 1,
            ],
          ],
          'maxItems' => 1,
          'minItems' => 1,
        ],
      ],
      'maxItems' => 1,
      'minItems' => 1,
    ],
  ],
];